import React from 'react';
import { useTranslation } from 'react-i18next';

const PersonalInfoRows = () => {
  const { t } = useTranslation();

  const getInitialRows = () => [
    {
      id: 1,
      fieldHEPrivateCard: t('FormsPage.firstName'),
      xPrivateCard: t('FormsPage.fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 2,
      fieldHEPrivateCard: t('FormsPage.lastName'),
      xPrivateCard: t('FormsPage.fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 3,
      fieldHEPrivateCard: t('FormsPage.picture'),
      xPrivateCard: t('FormsPage.fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 4,
      fieldHEPrivateCard: t('FormsPage.gender'),
      xPrivateCard: t('FormsPage.fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: 'gender',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 5,
      fieldHEPrivateCard: t('FormsPage.birthDate'),
      xPrivateCard: t('FormsPage.fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 6,
      fieldHEPrivateCard: t('FormsPage.residence'),
      xPrivateCard: t('FormsPage.fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 7,
      fieldHEPrivateCard: t('FormsPage.personalPhone'),
      xPrivateCard: t('FormsPage.fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 8,
      fieldHEPrivateCard: t('FormsPage.emergencyPhone'),
      xPrivateCard: t('FormsPage.fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 9,
      fieldHEPrivateCard: t('FormsPage.additionalPhone'),
      xPrivateCard: t('FormsPage.fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 10,
      fieldHEPrivateCard: t('FormsPage.serviceOrganization'),
      xPrivateCard: t('FormsPage.fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 11,
      fieldHEPrivateCard: t('FormsPage.previousWorkplace'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 12,
      fieldHEPrivateCard: t('FormsPage.previousJobRole'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 13,
      fieldHEPrivateCard: t('FormsPage.yearOfEmployment'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 14,
      fieldHEPrivateCard: t('FormsPage.timeSinceEmployment'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 15,
      fieldHEPrivateCard: t('FormsPage.performanceLevelPrevJob'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 16,
      fieldHEPrivateCard: t('FormsPage.previousTraining'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 17,
      fieldHEPrivateCard: t('FormsPage.trainingDuration'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 18,
      fieldHEPrivateCard: t('FormsPage.timeSinceTraining'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 19,
      fieldHEPrivateCard: t('FormsPage.trainingSuccessLevel'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
  ];

  return { getInitialRows };
};

export default PersonalInfoRows;
