import React from 'react';
import { getTranslation } from '../i18n';

const PersonalInfoRows = ({ language }) => {
  const t = (key) => getTranslation(key, language);

  const getInitialRows = () => [
    {
      id: 1,
      fieldHEPrivateCard: t('firstName'),
      xPrivateCard: t('fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 2,
      fieldHEPrivateCard: t('lastName'),
      xPrivateCard: t('fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 3,
      fieldHEPrivateCard: t('picture'),
      xPrivateCard: t('fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 4,
      fieldHEPrivateCard: t('gender'),
      xPrivateCard: t('fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: 'gender',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 5,
      fieldHEPrivateCard: t('birthDate'),
      xPrivateCard: t('fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 6,
      fieldHEPrivateCard: t('residence'),
      xPrivateCard: t('fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 7,
      fieldHEPrivateCard: t('personalPhone'),
      xPrivateCard: t('fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 8,
      fieldHEPrivateCard: t('emergencyPhone'),
      xPrivateCard: t('fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 9,
      fieldHEPrivateCard: t('additionalPhone'),
      xPrivateCard: t('fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 10,
      fieldHEPrivateCard: t('serviceOrganization'),
      xPrivateCard: t('fromSystem'),
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 11,
      fieldHEPrivateCard: t('previousWorkplace'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 12,
      fieldHEPrivateCard: t('previousJobRole'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 13,
      fieldHEPrivateCard: t('yearOfEmployment'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 14,
      fieldHEPrivateCard: t('timeSinceEmployment'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 15,
      fieldHEPrivateCard: t('performanceLevelPrevJob'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 16,
      fieldHEPrivateCard: t('previousTraining'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 17,
      fieldHEPrivateCard: t('trainingDuration'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 18,
      fieldHEPrivateCard: t('timeSinceTraining'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
    {
      id: 19,
      fieldHEPrivateCard: t('trainingSuccessLevel'),
      xPrivateCard: '',
      yPrivateCard: '',
      fieldENPrivateCard: '',
      classificationHEPrivateCard: '',
      beginningOfWorkPrivateCard: '',
      employersPrivateCard: '',
      reportsPrivateCard: '',
      improvementPrivateCard: '',
    },
  ];

  return { getInitialRows };
};

export default PersonalInfoRows;
